### ISSUE TITLE
MICe MINC additions?

### ISSUE THREAD

**Issue by bcdarwin** [vfonov/minc-toolkit-containers#1]
Hi Vlad -- if I created a pull request to add minc-stuffs and Pydpiper to this, would you consider including them?

**Comment by vfonov** [comment]
ok, I will take a look

**Comment by vfonov** [comment]
so, where is this pull request?

**Comment by bcdarwin** [comment]
Sorry, I've run into some problems with Python3.5 modules since the 16.04 Ubuntu Python packages are so old -- trying to create something minimal without e.g. compiling a fresh Python.  I'll try to get this to you sometime today.

**Comment by bcdarwin** [comment]
So far I haven't been able to get Pydpiper working in the 16.04 container since the Python3 toolchain there is so old ... it looks like I would have to either (a) make a new Python3 in that container or (b) use a more recent Ubuntu.  (a) would take longer to build the container so if you prefer I could create an 18.04 container instead?

**Comment by vfonov** [comment]
maybe it will be easier to switch to ubuntu 18.04
